---
- name: Install nagios plugins
  apt:
    name: nagios-plugins-basic

- name: Create group 'nagios'
  group:
    name: nagios
    system: true
    state: present

- name: Create user 'nagios'
  user:
    name: nagios
    group: nagios
    shell: /bin/bash
    home: /usr/local/nagios
    system: true
    state: present

- name: Add authorized key to nagios user
  ansible.posix.authorized_key:
    user: nagios
    state: present
    key: "{{ lookup('file', 'files/nagios.pub') }}"

- name: Create symlink to nagios plugins
  file:
    path: /usr/local/nagios/libexec
    state: link
    src: /usr/lib/nagios/plugins

- name: Download check_mem nagios plugin
  get_url:
    url: https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl
    dest: /usr/lib/nagios/plugins/check_mem.pl
    mode: "0755"
