- hosts: einstein
  remote_user: root
  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
        - 'o=${distro_id},a=${distro_codename}'
        - 'o=${distro_id},a=${distro_codename}-updates'
        - 'o=${distro_id},a=${distro_codename}-security'
      unattended_mail: 'mrspock@smrealms.de,daniel.hemberger@gmail.com'
      unattended_mail_only_on_error: true
      unattended_remove_unused_dependencies: true
      tags:
        - system
        - updates
    - role: Oefenweb.apt
      apt_dependencies:
        - python3-apt
      apt_upgrade: false
      apt_install:
        - git
        - vim
      tags:
        - system
        - packages
    - role: geerlingguy.docker
      docker_compose_version: 1.23.2
      tags:
        - system
        - docker
    - role: nagios
      tags:
        - system
        - nagios
    - role: setup-shell
      tags:
        - system
        - shell
    - role: setup-smr
      tags:
        - smr
        - game
    - role: setup-wiki
      tags:
        - smr
        - wiki
    - role: setup-beta
      tags:
        - smr
        - beta
    - role: setup-webboard
      tags:
        - smr
        - webboard
