---
- hosts: all
  remote_user: root
  roles:
    - role: hifis.unattended_upgrades
      unattended_origins_patterns:
        - o=${distro_id},a=${distro_codename}
        - o=${distro_id},a=${distro_codename}-updates
        - o=${distro_id},a=${distro_codename}-security
      unattended_mail: mrspock@smrealms.de,daniel.hemberger@gmail.com
      unattended_mail_only_on_error: true
      unattended_remove_unused_dependencies: true
      tags:
        - system
        - updates
    - role: geerlingguy.docker
      docker_package_state: latest
      docker_install_compose_plugin: true
      docker_install_compose: false
      tags:
        - system
        - docker
    - role: nagios
      tags:
        - system
        - nagios
    - role: system_config
      tags:
        - system
        - config
    - role: smr_live
      tags:
        - smr
        - live
    - role: smr_beta
      tags:
        - smr
        - beta
    - role: smr_wiki
      tags:
        - smr
        - wiki
    - role: smr_webboard
      tags:
        - smr
        - webboard
    - role: smr_chat_bridge
      tags:
        - smr
        - chat_bridge
