---
# This is used for both smr_live and smr_beta
twitter_consumer_key: "{{ vault_twitter_consumer_key }}"
twitter_consumer_secret: "{{ vault_twitter_consumer_secret }}"

google_client_id: "{{ vault_google_client_id }}"
google_client_secret: "{{ vault_google_client_secret }}"
