---
- name: Checkout git repository 'smrealms/smr'
  git:
    repo: http://github.com/smrealms/smr
    dest: "{{ beta_home_dir }}"
    version: main

- name: Expand and copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ beta_home_dir }}/{{ item.path }}"
    mode: u=rw,g=r,o=r
  with_community.general.filetree: "{{ 'files/' }}"
  when: item.state == 'file'

- name: Decrypt and copy opendkim files
  copy:
    src: files/opendkim
    dest: "{{ beta_home_dir }}"
    mode: u=rw,g=,o=

- name: Install a cron job to run the npc script
  cron:
    name: Run the beta NPC script
    special_time: hourly
    job: >
      cd {{ beta_home_dir }} &&
      LOGFILE=$(date "+/root/logs/beta_npc/\%Y-\%m-\%d/\%H-\%M-\%S.log") &&
      mkdir -p $(dirname $LOGFILE) &&
      /usr/local/bin/docker-compose run --rm npc > $LOGFILE 2>&1
