---
# tasks file for setup-webboard

- name: Checkout git repository 'smrealms/webboard'
  git:
    repo: https://github.com/smrealms/webboard.git
    dest: "{{ webboard_home_dir }}"
    version: master

- name: Copy and decrypt configuration files
  copy:
    src: files/
    dest: "{{ webboard_home_dir }}"

- name: Restrict config.php file permissions for phpbb
  file:
    path: "{{ webboard_home_dir }}/config.php"
    group: www-data
    mode: 0640

- name: Start webboard service and dependencies
  command: docker-compose up --detach webboard
  args:
    chdir: "{{ webboard_home_dir }}"
