---
# where smr beta repo will be installed
beta_home_dir: /root/beta

beta_mysql_host: beta-mysql
beta_mysql_user: smr
beta_mysql_database: smr_live
beta_mysql_root_password: "{{ vault_beta_mysql_root_password }}"
beta_mysql_password: "{{ vault_beta_mysql_password }}"

beta_recaptcha_public: 6LeC_SkUAAAAAMghYsszWLBoZzLAF92wCGdkF4Vg
beta_recaptcha_private: "{{ vault_beta_recaptcha_private }}"

beta_facebook_app_id: 977909275682435
beta_facebook_app_secret: "{{ vault_beta_facebook_app_secret }}"

beta_google_analytics_id: G-C4NJFCCE0S
