---
- name: Set up authorized keys for SSH access
  ansible.posix.authorized_key:
    user: root
    key: "{{ item }}"
  with_file:
    - ../../files/ssh-keys/travdan.pub
    - ../../files/ssh-keys/page.pub

- name: Install needed programs
  apt:
    pkg:
      - git
      - vim

- name: Force a color prompt
  lineinfile:
    path: /root/.bashrc
    insertafter: ^#force_color_prompt=.*$
    line: force_color_prompt=yes

- name: Make root color prompt red (so you know it's root)
  replace:
    path: /root/.bashrc
    regexp: 32m
    replace: 31m

- name: Source additional configurations in bashrc
  lineinfile:
    path: /root/.bashrc
    line: source /root/.bashrc_extra

- name: Copy rc files
  copy:
    src: files/
    dest: /root/
    mode: u=rw,g=,o=

- name: Make diff-highlight available for git
  copy:
    src: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
    dest: /usr/local/bin/diff-highlight
    remote_src: true
    mode: a+x

- name: Set system clock to the UTC timezone
  community.general.timezone:
    name: UTC

- name: Create a directory to output logs
  file:
    path: /root/logs
    state: directory
    mode: u=rwx,g=rx,o=

- name: Create cron entry for docker cleanup
  cron:
    name: docker cleanup
    special_time: daily
    job: docker image prune -f > /dev/null
