---
# tasks file for setup-beta

- name: Checkout git repository 'smrealms/smr'
  git:
    repo: git@github.com:smrealms/smr
    dest: "{{ beta_home_dir }}"
    version: main

- name: Expand and copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ beta_home_dir }}/{{ item.path }}"
  with_filetree: files/
  when: item.state == 'file'

- name: Decrypt and copy opendkim files
  copy:
    src: files/opendkim
    dest: "{{ beta_home_dir }}"

- name: Install a cron job to run the npc script
  cron:
    name: Run the beta NPC script
    special_time: hourly
    job: >
      cd {{ beta_home_dir }} &&
      LOGFILE=$(date "+/root/logs/beta_npc/\%Y-\%m-\%d/\%H-\%M-\%S.log") &&
      mkdir -p $(dirname $LOGFILE) &&
      /usr/local/bin/docker-compose run --rm npc > $LOGFILE 2>&1
