name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Create ansible secrets file
        run: |
            echo $ANSIBLE_VAULT_PASSWORD > ${{ github.workspace }}/.ansible_secret
        env:
            ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.15.0
